name: 🚀 Deploy
on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    pages: write
    contents: write

jobs:
    deploy:
        name: 🚀 Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 10

        env:
            SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
            SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
            SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
            VITE_SUPABASE_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
            VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
            VITE_APPLICATION_BASENAME: ${{ vars.VITE_APPLICATION_BASENAME }}
            VITE_IS_DEMO: ${{ vars.VITE_IS_DEMO }}


        steps:
            - name: 📥 Checkout repo
              uses: actions/checkout@v4

            - name: ⚙️ Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: ⚙️ Setup supabase
              uses: supabase/setup-cli@v1

            - name: 📥 Download deps
              run: npm install

            - name: 🔨 Build
              run: npm run build
            
            - name: 🔗 Supabase Link
              run: npx supabase link --project-ref $SUPABASE_PROJECT_ID

            - name: 📡 Push supabase migrations
              run: npx supabase db push

            - name: 📡 Deploy supabase functions
              run: npx supabase functions deploy

            - name: 📡 Deploy GitHub pages
              run: |
                  git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
                  git config --global user.email support+actions@github.com
                  git config --global user.name github-actions-bot 
                  npm run ghpages:deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
